- name: Configure NetQ-TS interfaces file
  copy:
    src: ../templates/interfaces
    dest: /etc/network/interfaces

- name: Apply host networking changes
  systemd:
    name: networking
    state: restarted
